#!/bin/bash

sudo sysctl -w net.ipv4.conf.eno1.rp_filter=0
sudo sysctl -w net.ipv4.conf.all.rp_filter=0
sudo sysctl -w net.ipv4.conf.default.rp_filter=0
sudo sysctl -w net.ipv4.conf.lo.rp_filter=0 

sudo sysctl -w net.ipv4.conf.all.forwarding=1
sudo sysctl -w net.ipv4.conf.default.forwarding=1
sudo sysctl -w net.ipv4.conf.eno1.forwarding=1
sudo sysctl -w net.ipv4.conf.lo.forwarding=1

sudo sysctl -w net.ipv6.conf.all.forwarding=1
sudo sysctl -w net.ipv6.conf.default.forwarding=1
sudo sysctl -w net.ipv6.conf.eno1.forwarding=1
sudo sysctl -w net.ipv6.conf.lo.forwarding=1

sudo sysctl -w net.ipv4.tcp_fwmark_accept=1

sudo sysctl -w net.ipv4.conf.all.forwarding=1
sudo sysctl -w net.ipv6.conf.all.forwarding=1
sudo sysctl -w net.ipv4.conf.all.send_redirects=0
sudo sysctl -w net.ipv6.conf.all.send_redirects=0
sudo iptables -F

sudo iptables -A PREROUTING -t nat -i eno1 -p tcp --dport 443 -j REDIRECT --to-port 8080

pushd $HOME/mitmproxy-filter
exec sudo mitmdump --showhost -k -s module_passthrough.py | grep PASS
